name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v3.1.0
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: build-jar
        run: mvn -B install
